Updated config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -51,7 +51,6 @@ jobs:
           path: coverage/
       - run:
          command: |
-          # Check if coverage file exists
           echo "Current working directory: $(pwd)"
           echo "Checking coverage directory: `ls -al coverage/`"
           if test -f "coverage/coverage.cobertura.xml"; then
@@ -59,14 +58,14 @@ jobs:
             $coverage = (Get-Content -Raw -Path coverage/coverage.cobertura.xml) -replace '.*tests="1" covered="([^"]+)".*', '$1'
             $threshold = 60
             if ($coverage -lt $threshold) {
-                Write-Host "Coverage is below threshold: $coverage%"
-                exit 1
+              Write-Host "Coverage is below threshold: $coverage%"
+              exit 1
             } 
             else {
-                Write-Host "Coverage is above threshold: $coverage%"
+              Write-Host "Coverage is above threshold: $coverage%"
             }
           else
-             echo "Coverage file not found"
+            echo "Coverage file not found"
             exit 1
           fi
          name: Check coverage
